baseurl = "https://www.bofh.org.uk/"
layoutdir = "layouts"
contentdir = "content"
publishdir = "public"
canonifyurls = "true"
theme = "hugo-tufte"
languageCode = "en-us"
title = "Just a Summary"
PygmentsCodeFences = true
pygmentsusecolors = true
pygmentsstyle = "monokai"
Paginate = 40
googleAnalytics = "UA-135014-1"

[markup.goldmark.renderer]
    unsafe = true

[[menu.topnav]]
    name = "Home"
    pre = "<i class='fa fa-home'></i> "
    weight = -110
    identifier = "home"
    url = "/"

[[menu.topnav]]
    name = "Bakehouse Diary"
    pre = "<i class='fa fa-book'></i> "
    url = "/series/bakehouse-diary"
    weight = 5

[[menu.topnav]]
    name = "Recordings"
    pre = "<i class='fa fa-music'></i> "
    url = "/series/repertoire-project"
    weight = 6

[[menu.topnav]]
    name = "Posts"
    pre = "<i class='fa fa-book'></i> "
    url = "/post/"
    weight = 10

[[menu.topnav]]
    name = "About Piers"
    url = "/pages/about/"
    pre = "<i class='fa fa-info-circle'></i> "
    weight = 20

[[menu.footer]]
    name = ""
    pre = "<i class='fa fa-github fa-2x'></i> "
    identifier = "github"
    url = "https://github.com/pdcawley/"
    weight = -100

[[menu.footer]]
    name = ""
    pre = "<i class='fa fa-twitter fa-2x'></i> "
    url = "https://twitter.com/pdcawley"
    identifier = "twitter"
    weight = -90

[[menu.footer]]
    name = ""
    pre = "<i class='fa fa-twitch fa-2x'></i> "
    weight = -80
    url = "https://twitch.tv/telear"
    identifer = "twitch"

[permalinks]
    post = "/:year/:month/:day/:slug"
    page = "/pages/:slug"

[blackfriday]
    hrefTargetBlank = false
    fractions = true

[taxonomies]
    series = "series"
    category = "categories"
    tag = "tags"

[params]
    Author = "<span class='given-name'>Piers</span> <span class='surname'>Cawley</span>"
    DateForm = "Jan 1, 2006"
    subtitle = "Piers Cawley practices punditry"
    copyrightHolder = "Piers Cawley"
    Description = "Piers Cawley practices punditry"
    stylesheet = "overrides.css"
    iso8601_format = "2006-01-02"
    pagination_size = 40
