baseurl = "http://www.bofh.org.uk/"
languageCode = "en-us"
title = "Just a Summary"
PygmentsCodeFences = true
pygmentsusecolors = true
pygmentsstyle = "monokai"
theme = "start-bootstrap-clean"
Paginate = 40
googleAnalytics = "UA-135014-1"

[[menu.main]]
    name = "Bakehouse Diary"
    url = "/series/bakehouse-diary"
    weight = 5

[[menu.main]]
    name = "Recordings"
    url = "/series/repertoire-project"
    weight = 6

[[menu.main]]
    name = "Archives"
    url = "/post/"
    weight = 10

[[menu.main]]
    name = "About Piers"
    url = "/pages/about/"
    weight = 20

[permalinks]
    post = "/:year/:month/:day/:slug"
    page = "/pages/:slug"

[blackfriday]
    hrefTargetBlank = false
    fractions = true

[taxonomies]
series = "series"

[params]
    Author = "Piers Cawley"
    DateForm = "Jan 1, 2006"
    Description = "Piers Cawley practices punditry"
    stylesheet = "overrides.css"
