baseurl = "https://bofh.org.uk/"
layoutdir = "layouts"
contentdir = "content"
publishdir = "public"
canonifyurls = "true"
theme = ["hugo-atom-feed", "hugo-tufte"]
languageCode = "en-gb"
title = "Just a Summary"
PygmentsCodeFences = true
pygmentsusecolors = true
pygmentsstyle = "monokai"
Paginate = 40
googleAnalytics = "UA-135014-1"

[mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputs]
    home = ["HTML", "RSS", "ATOM", "JSON"]

[author]
    homepage = "/"
    name = "Piers Cawley"
    given_name = "Piers"
    family_name = "Cawley"
    display_name = "Piers"

[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "atom" # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

[services.RSS]
    Limit = 40

[markup.goldmark.renderer]
    unsafe = true

[[menu.topnav]]
    name = "Home"
    pre = "<i class='fa fa-home'></i> "
    weight = -110
    identifier = "home"
    url = "/"

[[menu.topnav]]
    name = "Posts"
    pre = "<i class='fa fa-book'></i> "
    url = "/post/"
    weight = 10

[[menu.topnav]]
    name = "About Piers"
    url = "/pages/about/"
    pre = "<i class='fa fa-info-circle'></i> "
    weight = 20

[[menu.footer]]
    name = ""
    pre = "<i class='fa fa-github fa-2x'></i> "
    identifier = "github"
    url = "https://github.com/pdcawley/"
    weight = -100

[[menu.footer]]
    name = ""
    pre = "<i class='fa fa-twitter fa-2x'></i> "
    url = "https://twitter.com/pdcawley"
    identifier = "twitter"
    weight = -90

[[menu.footer]]
    name = ""
    pre = "<i class='fa fa-twitch fa-2x'></i> "
    weight = -80
    url = "https://twitch.tv/telear"
    identifer = "twitch"

[permalinks]
    post = "/:year/:month/:day/:slug"
    page = "/pages/:slug"

[taxonomies]
    series = "series"
    category = "categories"
    tag = "tags"

[params]
    Author = "<span class='given-name'>Piers</span> <span class='surname'>Cawley</span>"
    DateForm = "Jan 1, 2006"
    subtitle = "Piers Cawley practices punditry"
    copyrightHolder = "Piers Cawley"
    copyrightHoderEmail = "pdcawley@bofh.org.uk"
    Description = "Piers Cawley practices punditry"
    stylesheet = "overrides.css"
    iso8601_format = "2006-01-02T15:04:05Z0000"
    iso8601_html_format = "<span class='date'>2006-01-02</span><span class='time-sep'>T</span><span class='time-and-zone'><span class='time-part'>15:04:05</span><span class='zone-part'>Z0000</span></span>"
    pagination_size = 40
