baseurl = "https://bofh.org.uk/"
layoutdir = "layouts"
contentdir = "content"
publishdir = "public"
canonifyurls = "true"
theme = ["hugo-tufte"]
languageCode = "en-gb"
title = "Just a Summary"
googleAnalytics = "UA-135014-1"

summaryLength = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    noClasses = false

[mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[module]
    [[module.imports]]
      path = "github.com/kaushalmodi/hugo-jf2"
    [[module.imports]]
      path = "github.com/hugo-fixit/hugo-atom-feed"

[outputs]
    # home = ["HTML", "ATOM", "JF2Feed"]
    home = ["HTML", "JF2Feed", "atom"]
    # section = ["HTML", "ATOM", "JF2Feed"]
    section = ["HTML", "JF2Feed", "atom"]
    page = ["HTML", "JF2Post"]

[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "atom" # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

[services.RSS]
    Limit = 40

[[menu.topnav]]
    name = "Home"
    pre = "<i class='fa fa-home'></i> "
    weight = -110
    identifier = "home"
    url = "/"

[[menu.topnav]]
    name = "Posts"
    pre = "<i class='fa fa-newspaper-o'></i> "
    url = "/post/"
    weight = 10

[[menu.topnav]]
    name = "Reading"
    pre = "<i class='fa fa-book'></i> "
    url = "/book/"
    weight = 15

[[menu.topnav]]
    name = "About Piers"
    url = "/pages/about/"
    pre = "<i class='fa fa-info-circle'></i> "
    weight = 20

[[menu.footer]]
    name = ""
    pre = "<i class='fa fa-github fa-2x'></i> "
    identifier = "github"
    url = "https://github.com/pdcawley/"
    weight = -100

[[menu.footer]]
    name = ""
    pre = "<i class='fa fa-twitch fa-2x'></i> "
    weight = -80
    url = "https://twitch.tv/telear"
    identifer = "twitch"

[[menu.footer]]
    name = ""
    pre = "<i class='fa fa-mastodon fa-2x'></i> "
    weight = -110
    url = "https://mendeddrum.org/@pdcawley"
  identifier = "mastodon"

[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-youtube fa-2x'></i> "
  weight = -101
  url = "https://youtube.com/pierscawley"
  identifier = "youtube"

[permalinks]
    post = "/:year/:month/:day/:slug"
    page = "/pages/:slug"

[taxonomies]
    series = "series"
    category = "categories"
    tag = "tags"

[params]
    OldAuthor = "<span class='given-name'>Piers</span> <span class='surname'>Cawley</span>"
    DateForm = "Jan 1, 2006"
    subtitle = "Piers Cawley practices punditry"
    copyrightHolder = "Piers Cawley"
    copyrightHolderEmail = "pdcawley@bofh.org.uk"
    Description = "Piers Cawley practices punditry"
    iso8601_format = "2006-01-02T15:04:05Z0000"
    iso8601_html_format = "<span class='date'>2006-01-02</span><span class='time-sep'>T</span><span class='time-and-zone'><span class='time-part'>15:04:05</span><span class='zone-part'>Z0000</span></span>"
    pagination_size = 15
    microsub_url = "https://aperture.p3k.io/microsub/745"

  [params.feed]
    limit = 20
    fullText = true

  [params.section]
    [params.section.feed]
      limit = -1

  [params.list]
    [params.list.feed]
      limit = -1

  [params.author]
    homepage = "/"
    name = "Piers Cawley"
    given_name = "Piers"
    family_name = "Cawley"
    display_name = "Piers"
    note_html = "<span class='p-role'>FolkSinger</span>, photographer, carer and occasional programmer."
    [params.author.pronouns]
      nominative = "they"
      oblique = "him"
