((nil . ((org-babel-default-inline-header-args . ((:session . "none")
						  (:results . "replace")
						  (:exports . "code")
						  (:hlines . "yes")))))
 (org-mode . ((mode . visual-line)
	      (mode . visual-fill-column))))
