#+hugo_section: page/
#+hugo_base_dir: ../
#+hugo_auto_set_lastmod: t
#+startup: inlineimages
#+property: header-args:sql :session reporter :exports result :colnames yes :engine postgresql :results replace table
#+hugo_paired_shortcodes: %table %marginnote

#+seq_todo: TODO DRAFT DONE

* DONE About Piers
:PROPERTIES:
:export_hugo_slug: about
:EXPORT_FILE_NAME: about
:EXPORT_DATE: 2003-01-01
:END:

** Baker
I used to be a programmer. I was good at it, but I kind of grew to hate it as a means of making a living, so when RSI came calling and made it near-impossible to type for more than about half an hour before I had to take a 45 minute break, I got properly serious about breadmaking. So since Christmas 2017 I've been baking sourdough bread for money as [[https://loafery.co.uk][The Loafery]]. It's not (remotely) as lucrative as programming was, but it's infinitely more satisfying. And tasty.

Sadly COVID has done for the bakery, so I'm back to baking occasionally at home. My sleep pattern is delighted by this.

** Programmer
I was a Perl programmer for well over 10 years, spent a few years as a Ruby programmer before returning to the Perl fold. These days, what little code I write is usually in some sort of Lisp.

** [[http://flickr.com/photos/pdcawley/sets/807230][Photographer]]
Discovering that you are good at something is wonderful. I was working in Amsterdam on one of my first programming gigs and commuting back to England most weekends. One day, passing through duty free, I bought myself a cheapish Nikon SLR, loaded it up with black and white film and was almost immediately hooked. Through the simple expedient of burning lots and lots of film and ruthless editing of contact sheets, I got better at it.

Of the images in the portfolio linked to, only one was taken with that first camera; see if you can guess which one it is.

** Singer
Singing is comfort food for my soul. Singing is something to be shared. And, because I sing traditional songs, I don’t have to worry about licensing issues if I want to distribute any recordings I make.

Traditional songs — free software for the soul.

Pretentious? Moi?

** Cook

Mmm… Chinese food.

** All round geek

Look: I have a weblog; I’ve had the same email address since 1996; I’ve never met the majority of my friends in person; I ran my bakery with Emacs; I’d rather spend an evening hacking on the laptop than watching TV. What else could I be?

* DONE Tamlyn.co.uk
:PROPERTIES:
:export_hugo_slug: about/tamlyn-co-uk
:EXPORT_FILE_NAME: tamlyn-co-uk
:END:
Hi, you ended up here because you visited tamlyn.co.uk, which is a domain my wife and I have been using for private email since 1998, but which we've never bothered setting up a website for.

It's possible that you were looking for the UK arm of [[https://tamlyn.com][Tamlyn.com]], which appears to be building supplies manufacturer based in Texas. If so, you should head on over to their UK site, [[https://tamlyn.uk][tamlyn.uk]].

By the way, if you're in Texas, maybe consider supporting the work of [[https://linktr.ee/lambda_legal][Lambda Legal]], [[https://outyouth.org][Out Youth]], [[https://www.myresourcecenter.org/community/lgbtq-youth-programs/][Resource Centre]] and other organisations working for LGBTQIA+ kids in the state.

* DONE Wishlist
:PROPERTIES:
:export_hugo_slug: about/wishlist
:EXPORT_FILE_NAME: wishlist
:export_date: 2024-08-01
:END:

Amazon no longer allow you to link anything but stuff they sell in their wishlists, which is less than ideal, so here goes with a list of stuff I would really like.

** Music and Streaming

This is the horribly expensive section. Sorry.

*** [[https://www.eastwoodsoundandvision.com/blackmagic-design-atem-mini-extreme-iso][BlackMagic ATEM Mini Extreme ISO Switcher]]

This is an upgrade for the ATEM Mini Pro ISO that runs my YouTube streams, and it would enable me to do a lot of stuff that's currently either fiddly or outright impossible. It has more buttons than you can shake a stick at. It's a cut down version of the console that sits in a TV control room which the editor uses to cut from camera to camera, add graphics overlays, set up split screen displays and generally run the entire show from their desk. It also handles sending the live stream out to the internet and records every input channel, to allow for later editing.

I don't /need/ one of these -- my Mini Pro has been doing excellent service since I bought it -- but I really /want/ one.

*** [[https://www.gear4music.com/PA-DJ-and-Lighting/Mackie-Thump-GO-Portable-Battery-Powered-Speaker/41RC][Mackie Thump Go]] Portable PA
Emily and I have been experimenting with using a looper to layer up extra harmonies when we're performing. It sounds grand, but the catch is that it requires a PA. Some venues have PAs, but many folk venues don't. Also, it's always nicer to practice without headphones on, so a small PA of our own would be very useful.

*** [[https://shop.funky-junk.com/shop/recording/microphones/condenser/solid-state/ear-trumpet-labs-myrtle-condenser-microphone/][Ear Trumpet Labs Myrtle]] Microphone

ETL microphones look fantastic and are designed for the kind of music Emily and I make. In the US bluegrass and americana scene they're almost the de facto choice for small ensembles doing the old school 'bunch of performers around a single mic' style of performing.

** A course of some description

There's so much to learn, isn't there?

*** Cookery

I've enjoyed [[https://rivercottage.net][River Cottage]] pig related courses, and their fermentation or curing and smoking courses look very tempting.


I like to think I know what I'm doing with a knife, but a [[https://www.rutlandcookeryschool.co.uk/courses/knife-skills-full-day.html][Knife Skills]] course would go down well.


*** Crafts

This [[https://www.craftcourses.com/courses/kitchen-knife-course-1][Kitchen Knife]] making course looks fab.

I'd also love to take JoJo Wood's [[https://www.pathcarvers.co.uk/product/eating-spoon-masterclass-with-jojo-wood/][Eating Spoon Masterclass]] course, but I'm not sure if it's started up again post-COVID. Gill and I did a couple of her dad's courses in Edale where we met and were very impressed by her.


*** Photography
I realise I'm never likely to set up my own darkroom, but I'd love to learn to use one so I can hire one occasionally. The Art House in Wakefield has a [[https://the-arthouse.org.uk/workshops/darkroom-printing-taster-session/][Taster Session]], as well as a [[https://the-arthouse.org.uk/darkroom-one-to-one/][Darkroom One-to-One]] option that looks very tempting, and Wakefield's close enough to Doncaster that their [[https://the-arthouse.org.uk/maker-spaces/darkroom/][Darkroom membership]] looks pretty handy too.

Not quite a traditional darkroom process, but I'd also love to learn [[https://highlandprintstudio.co.uk/classes/photopolymer-gravure/][Photogravure]], which is a cunning technique for printing photos on an etching press to gorgeous effect.

*** Music

On the music front, this [[https://www.tickettailor.com/events/stonesbarn/1066362][Performance & Repertoire Skills]] with Maddy Prior(!) course looks amazing and absolutely up my street (though possibly a little short notice as a birthday present in 2024. If you do decide to go for it, could you let Gill know in advance.)

** Kitcheny Things

*** [[https://michaelmayknives.com/product/chefs-knife-yorkshire-oak/][A Chef's Knife]] by Michael May

Michael May's a Sheffield knife maker who makes gorgeous knives. I have one of his pocket knives and it's always with me. He recently started making a range of kitchen knives as well, and they're spectacular. Any of his [[https://michaelmayknives.com/product-category/kitchen/][kitchen knives]] would be a delightful thing to have, but I'm an absolute sucker for a chef's knife.

Even if you're not thinking of buying one of these for me, check out the rest of the site and try to resist buying one for yourself -- you never know when you'll need a pocket knife that really cuts.

*** [[https://www.amazon.co.uk/T-1-Kitchen-Sharpener-Version-Patented/dp/B0CNKQK9NV/][A Tormek T-1]] Kitchen Knife Sharpener

I'm not denying that this is complete overkill, but I do like a sharp knife, and I would be honour bound to sharpen any kitchen knife you brought to me for the foreseeable future.

*** Almost anything from [[https://souschef.co.uk][Sous Chef]]
I'm a sucker for a good cookbook. The chocolate and sweets collection is amazing, and I wouldn't say no to a [[https://www.souschef.co.uk/products/microplane-gourmet-extra-coarse-grater][Microplane coarse cheese grater]].

*** Almost anything from [[https://chocolarder.com/][Chocolarder]]
When we lived in Cornwall, we met Mike, the founder of Chocolarder back when he was making small amounts of chocolate in his garden shed and selling them at farmers' markets. I was a sucker for pretty much everything he made, but his [[https://www.chocolarder.com/shop/sea-salt-caramel-truffles/][Sea Salt Caramel Truffles]] were amazing. They still are. It's a little harder to impulse buy stuff from them now we're living up country again.

** Stationery

There's something about a good pen and the paper to use it on. Lots of lovely stuff at [[https://cultpens.com][Cult Pens]], including:

*** [[https://cultpens.com/products/kaweco-liliput-fireblue-fountain-pen][Kaweco Liliput Fireblue Fountain Pen]]

The perfect fountain pen doesn't exist, but these are gorgeous and I'd love to have one in the pen loop of my pocket notebook. A fine nib, please -- I'll be using this with a small pocket notebook and writing small.

***  [[https://cultpens.com/products/pilot-parallel-pen][Pilot Parallel Pen]]
Because sometimes, I just want to muck about with a really wide italic type nib

*** [[https://cultpens.com/products/opus-88-mini-pocket-pen-fountain-pen-check][Opus 88 Mini]]
Another pocket fountain pen option. Fine nib.

*** Rhodia [[https://cultpens.com/products/rhodia-rhodiarama-softcover-notebook-a5][Notebooks]] and [[https://cultpens.com/collections/rhodia-dotpad-notepads][Pads]]
Just the nicest paper for writing on with ink pens.

*** [[https://cultpens.com/collections/fountain-pen-ink][Ink]]
I'm still searching for the perfect sepia ink. Something that looks like it was written 200 years ago and has dried to the perfect dark brown. I have the horrible feeling that the only way to achieve that look is with some [[https://cultpens.com/products/kwz-iron-gall-ink-60ml][iron/gall]] concoction that's then been left for a long time so the original colour vanishes to be replaced by the permanent colour that comes from the iron/gall reaction. Any colour but green, really.

* DONE Joining Twitch as a viewer
:PROPERTIES:
:EXPORT_FILE_NAME: twitch-viewing
:export_hugo_slug: twitch-viewing
:EXPORT_DATE: 2022-03-24
:END:
  There are multiple platforms available where you can watch and interact with people sharing music;  how to play their favourite video game; tips on sewing makeshift surgical masks; and a bewildering panoply of other stuff. If you're after carefully edited, scripted and polished stuff, then [[https://youtube.com][YouTube]] and [[https://vimeo.com/][Vimeo]] are the websites for you. If you're after something a little more loose and interactive, where you can ask questions and give immediate feedback and the like, then [[https://twitch.tv/][Twitch.tv]] could easily be Your Place.


** Just watching anonymously
   You /can/ treat Twitch as just another TV channel -- find something that interests you and just watch. But, if you're anything like I was when I first started watching people playing [[https://dwarffortresswiki.org/][Dwarf Fortress]] to pick up tips on how to avoid killing all my dwarfs quite so quickly, you will end up wanting to ask questions. You might fancy chucking them the digital equivalent of a few coins, or paying a subscription to support their work. To do that, you're going to need a Twitch account.

A word to the wise; once you set up the account, Twitch will suggest (in manner that seems to imply that there is no alternative) that you download their desktop app. You don't need to do this. I have the Twitch app on my mobile devices, but on a desktop system, everything works brilliantly from the browser and I suggest you stick with that.

*** Signing up with Amazon Prime

   If you're an Amazon Prime subscriber, subscribe via [[https://twitch.amazon.com/prime][twitch.amazon.com/prime]] and Amazon will let you subscribe to one favoured Twitch streamer for free. You don't pay a penny, but they get paid as if you'd taken out a basic subscription. The only catch is that these subscriptions do not autorenew. You have to resubscribe every month, or subscribe to someone else if you feel like spreading the love.[fn:1]

*** Signing up without Amazon Prime

    No Amazon Prime? No matter, [[https://twitch.tv/signup][twitch.tv/signup]] is the place to go. It's a pretty straightforward free account. You can make a dedicated Twitch account (which would be my choice) or you can just login with Facebook.


** Using your account

   Once you have an account, you can start to participate in the chat associated with the channels you're watching. You can follow people and get notifications when they come on line (I confess, I turn the notifications off, but my default page when I go to Twitch is [[https://twitch.tv/following/live][twitch.tv/following/live]], which shows me which of my favourites are online at the moment.

   Now you've got an account, there's nothing to stop you streaming yourself; if you are, in any way, a singer, I can't recommend downloading [[https://twitch.tv/sings/download][Twitch Sings]] and having a play. Lots of great karaoke tunes to have a crack at, join in with other singers and share duet seeds so they can join in with you, and if you fancy going live, there's a big friendly button down in the bottom left hand corner that will get you online with nothing extra to download. Find out if you enjoy yourself before fiddling with all the extra software.

   But you don't /have/ to stream; I was on Twitch for the best part of a year, just occasionally hanging in streamers' chats and passing the time of day before I bit the bullet and started to stream myself. Some corners of the site have rather more assholes per square inch than others (popular shooty bang games, I'm looking at you) but if you're like me and enjoy the crafty and artistic areas, you're going to find some really lovely communities to join. Just have a great time!


* Footnotes

[fn:1] Obviously, I'd love it it you subscribed to my channel, but I also like the idea of everyone passing a little of the money that would otherwise be going into Amazon's gaping money maw on to any independent creator at all, whether it's me or not.
