name: GitHub Pages

on:
  push:
    branches:
      - main
env:
  emacs-version: 28.1

jobs:
  deploy:

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache Nix installs
        uses: actions/cache@v3.0.2
        env:
          cache-name: cache-nix-installs
        with:
          path: /nix
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.emacs-version }}

      - name: Clone Org-mode exporter
        run: git clone https://github.com/kaushalmodi/ox-hugo.git ~/ox-hugo

      - name: Clone restclient.el
        run: git clone https://github.com/pdcawley/restclient.el.git ~/restclient

      - name: And ob-restclient.el
        run: git clone https://github.com/pdcawley/ob-restclient.el.git ~/ob-restclient

      - name: And json-mode
        run: git clone https://github.com/joshwnj/json-mode.git ~/json-mode

      - name: Setup emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ env.emacs-version }}

      - name: Set EMACSLOADPATH
        run: echo "EMACSLOADPATH=$HOME/ox-hugo:$HOME/restclient:$HOME/ob-restclient:$HOME/json-mode" >> $GITHUBENV

      - name: Prep .emacs.d for ox-hugo because ???
        run: mkdir -p ~/.emacs.d

      - name: export posts from Org
        run: emacs ./org-content/all-posts.org --batch -q -l restclient.el -l ob-restclient.el -l ox-hugo.el --eval='(progn (setq org-confirm-babel-evaluate nil) (org-hugo-export-wim-to-md t))' --kill

      - name: export pages from Org
        run: emacs ./org-content/all-pages.org --batch -q -l restclient.el -l ob-restclient.el -l ox-hugo.el --eval='(org-hugo-export-wim-to-md t)' --kill

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: setup known_hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo --minify --buildFuture

      - name: Copy to server
        run: rsync -avz --del -e "ssh -p ${{secrets.SSH_PORT}}" ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:bofh.org.uk
