name: GitHub Pages

on:
  push:
    branches:
      - main
env:
  emacs-version: 28.1

jobs:
  deploy:

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ env.emacs-version }}

      - name: Prep .emacs.d for ox-hugo because ???
        run: mkdir -p ~/.emacs.d
        
      - name: Cache ~/.emacs.d
        uses: actions/cache@v3.0.2
        with:
          path: ~/.emacs.d
          key: ${{ runner.os }}-emacs.d-${{ hashfiles('setup-org-export.el') }}

      - name: export posts from Org
        run: emacs ./org-content/all-posts.org --batch -q -L $GITHUB_WORKSPACE -l setup-org-export --eval='(progn (setq org-confirm-babel-evaluate nil) (org-hugo-export-wim-to-md t))' --kill

      - name: export pages from Org
        run: emacs ./org-content/all-pages.org --batch -q -L $GITHUB_WORKSPACE -l setup-org-export --eval='(org-hugo-export-wim-to-md t)' --kill

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: setup known_hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo --minify --buildFuture

      - name: Copy to server
        run: rsync -avz --del -e "ssh -p ${{secrets.SSH_PORT}}" ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:bofh.org.uk

#      - name: Send Webmentions
#        uses: joelwmale/webhook-action@master
#        with:
#          url: ${{ secrets.WEBHOOK_URL }}
#          headers: '{"repository": "pdcawley/bofh.org.uk"}'
#          body: '{"event": "deployment", "repository": "pdcawley/bofh.org.uk"}'
